<?php

namespace Payment\PaymentBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * paymentOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class paymentOrderRepository extends EntityRepository
{
}
