<?php

namespace docroms\Bundle\PaymentBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * paymentCouponRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class paymentCouponRepository extends EntityRepository
{
}
