<?php

namespace docroms\Bundle\PaymentBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * paymentProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class paymentProfileRepository extends EntityRepository
{
}
